### PR TITLE
Make counsel-etags work better with remote connections

### PR DESCRIPTION
**Pull request by cwinsnes**
* Use `start-file-process` to allow for different handler based on connection type.
* Use local paths instead of connection strings so `TAGS` can be read properly both locally and remotely.
* If Tramp is available and the file is remote, flush Tramp caches to find `TAGS` faster.

### CODE REVIEW

**Comment by cwinsnes** [comment]
A small issue with this version is that if you are calling `counsel-etags-find-tag-at-point` without an available `TAGS` file on a Tramp connection, the TAGS file will be created like it should but you will have to call `counsel-etags-find-tag-at-point` *again* to get the actual tags suggestions.

I believe this is due to some file-caching issue making the initial call not able to find the TAGS file and trying to open `nil` when performing `counsel-etags-execute-collect-function`. On the second call, the TAGS are found without issue. I have been unable to correct this issue.

**Comment by redguardtoo** [comment]
@cwinsnes I know this issue. No worry about it.

btw, could you squash your commits into one commit and force push the code?

**Comment by cwinsnes** [comment]
Commits are squashed and force-pushed.

**Comment by redguardtoo** [comment]
Thank you

**Pull request merged**
